/**
 * NotificationService - Centralized notification management system.
 * Orchestrates all notification operations including scheduling, cancellation,
 * permissions, channels, and boot persistence.
 */

import { notificationChannels } from './NotificationChannels';
import { notificationPermissions } from './NotificationPermissions';
import { notificationScheduler } from './NotificationScheduler';
import { notificationLogger } from './NotificationLogger';
import { daySyncNotificationBridge } from './DaySyncNotificationBridge';
import type {
  NotificationData,
  EventReminderData,
  DailyReminderData,
  ScheduleResult,
  CancelResult,
  PermissionStatus,
} from './types';
import {
  NotificationChannel,
  NotificationType,
} from './types';

/**
 * NotificationService class - Main entry point for all notification operations.
 */
class NotificationService {
  private initialized = false;

  /**
   * Initialize the notification service.
   * Should be called once during app startup.
   */
  async initialize(): Promise<void> {
    if (this.initialized) {
      notificationLogger.debug('NotificationService already initialized');
      return;
    }

    try {
      notificationLogger.info('Initializing NotificationService');

      // Initialize channels
      await notificationChannels.initialize();

      // Check permissions
      const status = await notificationPermissions.checkPermissions();
      notificationLogger.info('Initial permission status', { status });

      this.initialized = true;
      notificationLogger.info('NotificationService initialized successfully');
    } catch (error) {
      notificationLogger.error('Failed to initialize NotificationService', {
        error: error instanceof Error ? error.message : String(error),
      });
      throw error;
    }
  }

  /**
   * Check if the service is initialized.
   */
  isInitialized(): boolean {
    return this.initialized;
  }

  // ==================== PERMISSIONS ====================

  /**
   * Check current notification permission status.
   */
  async checkPermissions(): Promise<PermissionStatus> {
    return notificationPermissions.checkPermissions();
  }

  /**
   * Request notification permissions.
   */
  async requestPermissions(): Promise<PermissionStatus> {
    return notificationPermissions.requestPermissions();
  }

  /**
   * Check if notifications are permitted.
   */
  async isPermitted(): Promise<boolean> {
    return notificationPermissions.isPermitted();
  }

  // ==================== EVENT REMINDERS ====================

  /**
   * Schedule an event reminder notification.
   */
  async scheduleEventReminder(data: EventReminderData): Promise<ScheduleResult> {
    if (!data.reminderMinutes || data.reminderMinutes <= 0) {
      notificationLogger.debug('Skipping event reminder: no reminder minutes', { eventId: data.eventId });
      return { success: true, ids: [] };
    }

    const [hours, minutes] = data.time.split(':').map(Number);
    const eventDate = new Date(data.date);
    eventDate.setHours(hours, minutes, 0, 0);

    const triggerDate = new Date(eventDate.getTime() - data.reminderMinutes * 60 * 1000);

    // Don't schedule if trigger is in the past
    if (triggerDate <= new Date()) {
      notificationLogger.debug('Skipping event reminder: trigger time in the past', {
        eventId: data.eventId,
        triggerDate,
      });
      return { success: true, ids: [] };
    }

    const key = `event:${data.eventId}`;
    const notificationData: NotificationData = {
      id: 0, // Will be generated by scheduler
      title: 'DaySync — Promemoria',
      body: `${data.title} tra ${data.reminderMinutes} minuti`,
      channelId: NotificationChannel.EVENT_REMINDERS,
      smallIcon: 'ic_notification',
      sound: data.soundEnabled ? 'default' : undefined,
      type: NotificationType.EVENT_REMINDER,
      extra: { eventId: data.eventId },
      deepLink: `/Agenda?date=${data.date}`,
      scheduleAt: triggerDate,
      allowWhileIdle: true,
    };

    const result = await notificationScheduler.schedule(notificationData, key);
    // Silent background sync with exact AlarmManager rescheduler on Android
    await daySyncNotificationBridge.rescheduleAll();
    return result;
  }

  /**
   * Cancel an event reminder notification.
   */
  async cancelEventReminder(eventId: string): Promise<CancelResult> {
    const result = await notificationScheduler.cancelByKey(key);
    // Sync cancel with native rescheduler
    await daySyncNotificationBridge.rescheduleAll();
    return result;
  }

  // ==================== DAILY REMINDERS ====================

  /**
   * Schedule a daily reminder notification.
   */
  async scheduleDailyReminder(data: DailyReminderData): Promise<ScheduleResult> {
    const key = `daily:${data.type}:${data.slotId}`;
    const scheduleDate = new Date();
    scheduleDate.setHours(data.hour, data.minute, 0, 0);
    
    const notificationData: NotificationData = {
      id: 0,
      title: data.title,
      body: data.body,
      channelId: NotificationChannel.DAILY_REMINDERS,
      smallIcon: 'ic_notification',
      sound: data.soundEnabled ? 'default' : undefined,
      type: data.type === 'morning' ? NotificationType.DAILY_MORNING : NotificationType.DAILY_EVENING,
      scheduleAt: scheduleDate,
      repeats: true,
      allowWhileIdle: true,
    };

    return notificationScheduler.schedule(notificationData, key);
  }

  /**
   * Cancel a daily reminder notification.
   */
  async cancelDailyReminder(slotId: number): Promise<CancelResult> {
    const keys = [`daily:morning:${slotId}`, `daily:evening:${slotId}`];
    let totalCancelled = 0;
    const errors: string[] = [];

    for (const key of keys) {
      const result = await notificationScheduler.cancelByKey(key);
      if (result.success) {
        totalCancelled += result.count;
      } else {
        errors.push(result.error || 'Unknown error');
      }
    }

    return {
      success: errors.length === 0,
      count: totalCancelled,
      error: errors.length > 0 ? errors.join('; ') : undefined,
    };
  }

  /**
   * Sync all daily reminders based on settings.
   */
  async syncDailyReminders(settings: {
    dailyMorningEnabled: boolean;
    morningHour: number;
    morningMinute: number;
    morningTitle: string;
    morningBody: string;
    dailyEveningEnabled: boolean;
    eveningHour: number;
    eveningMinute: number;
    eveningTitle: string;
    eveningBody: string;
    dailySound: boolean;
  }): Promise<void> {
    try {
      notificationLogger.info('Syncing daily reminders', { settings });

      // Cancel existing daily reminders
      await this.cancelDailyReminder(900); // Morning slot
      await this.cancelDailyReminder(1800); // Evening slot

      // Schedule morning reminder
      if (settings.dailyMorningEnabled) {
        await this.scheduleDailyReminder({
          slotId: 900,
          type: 'morning',
          hour: settings.morningHour,
          minute: settings.morningMinute,
          title: settings.morningTitle,
          body: settings.morningBody,
          soundEnabled: settings.dailySound,
        });
      }

      // Schedule evening reminder
      if (settings.dailyEveningEnabled) {
        await this.scheduleDailyReminder({
          slotId: 1800,
          type: 'evening',
          hour: settings.eveningHour,
          minute: settings.eveningMinute,
          title: settings.eveningTitle,
          body: settings.eveningBody,
          soundEnabled: settings.dailySound,
        });
      }

      notificationLogger.info('Daily reminders synced successfully');
    } catch (error) {
      notificationLogger.error('Failed to sync daily reminders', {
        error: error instanceof Error ? error.message : String(error),
      });
      throw error;
    }
  }

  // ==================== GENERAL NOTIFICATIONS ====================

  /**
   * Schedule a custom notification.
   */
  async scheduleNotification(data: NotificationData, key: string): Promise<ScheduleResult> {
    return notificationScheduler.schedule(data, key);
  }

  /**
   * Cancel a notification by key.
   */
  async cancelNotification(key: string): Promise<CancelResult> {
    return notificationScheduler.cancelByKey(key);
  }

  /**
   * Cancel all notifications.
   */
  async cancelAllNotifications(): Promise<CancelResult> {
    return notificationScheduler.cancelAll();
  }

  /**
   * Get pending notifications.
   */
  async getPendingNotifications(): Promise<Array<{ id: number; title: string; body: string }>> {
    return notificationScheduler.getPending();
  }

  /**
   * Get scheduled notification count.
   */
  getScheduledCount(): number {
    return notificationScheduler.getScheduledCount();
  }

  // ==================== CHANNELS ====================

  /**
   * Get all channel configurations.
   */
  getChannelConfigs() {
    return notificationChannels.getAllChannelConfigs();
  }

  /**
   * List all channels.
   */
  async listChannels(): Promise<NotificationChannel[]> {
    return notificationChannels.listChannels();
  }

  // ==================== LOGGING ====================

  /**
   * Get notification logs for debugging.
   */
  getLogs() {
    return notificationLogger.getLogs();
  }

  /**
   * Get notification log statistics.
   */
  getLogStats() {
    return notificationLogger.getStats();
  }

  /**
   * Export logs as JSON.
   */
  exportLogs(): string {
    return notificationLogger.exportLogs();
  }

  /**
   * Clear notification logs.
   */
  clearLogs(): void {
    notificationLogger.clear();
  }

  /**
   * Subscribe to log changes.
   */
  subscribeToLogs(listener: (logs: any[]) => void): () => void {
    return notificationLogger.subscribe(listener);
  }

  // ==================== NATIVE BRIDGING (Android Exact Alarms & Battery) ====================

  /**
   * Reschedule all exact alarms on Android.
   */
  async rescheduleAll(): Promise<void> {
    await daySyncNotificationBridge.rescheduleAll();
  }

  /**
   * Check if exact alarm permission is granted.
   */
  async checkExactAlarmPermission(): Promise<boolean> {
    const res = await daySyncNotificationBridge.checkExactAlarmPermission();
    return res.granted;
  }

  /**
   * Request exact alarm permission setting screen.
   */
  async requestExactAlarmPermission(): Promise<boolean> {
    const res = await daySyncNotificationBridge.requestExactAlarmPermission();
    return res.triggered;
  }

  /**
   * Check if battery optimization is ignored.
   */
  async checkBatteryOptimizations(): Promise<boolean> {
    const res = await daySyncNotificationBridge.checkBatteryOptimizations();
    return res.ignoring;
  }

  /**
   * Open battery optimizations screen.
   */
  async requestIgnoreBatteryOptimizations(): Promise<boolean> {
    const res = await daySyncNotificationBridge.requestIgnoreBatteryOptimizations();
    return res.triggered;
  }
}

// Singleton instance
export const notificationService = new NotificationService();
